modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/TeamBR-Modding/AssistedProgression/issues"
license="http://creativecommons.org/licenses/by-nc-sa/4.0/"

[[mods]]
  modId="assistedprogression"
  namespace="assistedprogression"
  version="${version}"
  displayName="Assisted Progression"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/assisted-progression"
  authors="pauljoda, Dyonovan"
  description='''
  Small things to help you along
  '''
  [[dependencies.assistedprogression]]
      modId="nucleus_teambr"
      mandatory=true
      versionRange="[1.16.2,)"
      ordering="BEFORE"
      side="BOTH"
